project:
  type: website
  output-dir: docs
  
website:
  title: "Job Market Analysis 2024"
  navbar:
   background: "#002147"
   search: true
   left:
     - href: index.qmd
       text: "Home"
     - href: introduction.qmd
       text: "Project Overview"
     - href: data_cleaning.qmd
       text: "Data Preparation"
     - href: eda.qmd
       text: "Exploratory Analysis"
     - href: skill_gap_analysis.qmd
       text: "Skill Gap Analysis"
     - href: salary_analysis.qmd
       text: "Salary Analysis"
     - href: MLR.qmd
       text: "Predictive Modeling"
     - href: career_plan.qmd
       text: "Career Strategy"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
execute:
  echo: true
  eval: true
  code-fold: true